
global:
    ip_pattern: '192.168.100.10'
    store: '10'
    provider: 'vmware' #'vbox'
    esxi_hostname: 'ip.or.host.fqdn'
    esxi_username: 'someuser'
    esxi_password: 'somepass'



boxes:

    nodeDoc18:
        box:
            box: 'bento/ubuntu-18.04'
            cpus: '4'
            mem: '4096'
            provision: ./ansible/nodebuntu/bootstrap.yml

    # nodeDoc19:
    #     box:
    #         box: 'bento/ubuntu-19.10'
    #         cpus: '4'
    #         mem: '4096'
    #         provision: ./ansible/nodebuntu/bootstrap.yml
    #         disk_path: './sata.vdi'


        