
global:
    ip_pattern: '192.168.100.10'
    store: 15
    provider:  'vbox'
    #esxi_hostname: 'ip.or.host.fqdn'
    #esxi_username: 'someuser'
    #esxi_password: 'somepass'



boxes:

    nodeDoc18:
        box:
            box: 'ubuntu/bionic64'
            cpus: '4'
            mem: '4096'
            provision: ./nodeDoc/bootstrap.yml
            disk_path: './sata.vdi'

    # nodeDoc19:
    #     box:
    #         box: 'bento/ubuntu-19.10'
    #         cpus: '4'
    #         mem: '4096'
    #         provision: ./ansible/nodebuntu/bootstrap.yml
    #         disk_path: './sata.vdi'


        