
global:
    cpus: 2
    mem: 2048
    ip_pattern: '192.168.99.10'

boxes:
    nodeCent:
        box:
            box: 'centos/7'
            default_root: 'vagrant' 
            newdisk_path: './bootstrap/disk.vdi'
            newdisk_size: 1 #GB
            provision: "./bootstrap/cent/bootstrap.yml"

    nodeUbu:
        box:
            box: 'ubuntu/bionic64'
            default_root: 'vagrant' 
            provision: "./bootstrap/ubu/bootstrap.yaml"
        
    # nodeintruder:
    #     box:
    #         box: 'kalilinux/rolling'
    #         default_root: 'kali'


        